store/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart_summary, name="cart_summary"),
	path('add/', views.cart_add, name="cart_add"),
	path('delete/', views.cart_delete, name="cart_delete"),
	path('update/', views.cart_update, name="cart_update"),
]

store/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
	path('', views.index, name='index'),
	path('index/', views.index, name='index'),
	path('contact/', views.contact, name='contact'),
	path('category/<str:foo>', views.category, name='category'),
	path('product-detail/<int:pk>', views.product_detail, name='product-detail'),
	path('update_user/', views.update_user, name='update_user'),
	path('update_password/', views.update_password, name='update_password'),
	path('update_info/', views.update_info, name='update_info'),
	path('login/', views.login_user, name='login'),
	path('logout/', views.logout_user, name='logout'),
	path('register/', views.register_user, name='register'),
	path('category_summary/', views.category_summary, name='category_summary'),
	path('search/', views.search, name='search'),
]

store/payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
	path('payment_success', views.payment_success, name='payment_success'),
	path('payment_failed', views.payment_failed, name='payment_failed'),
	path('checkout', views.checkout, name='checkout'),
	path('billing_info', views.billing_info, name='billing_info'),
	path('process_order', views.process_order, name='process_order'),
	path('shipped_dash', views.shipped_dash, name='shipped_dash'),
	path('not_shipped_dash', views.not_shipped_dash, name='not_shipped_dash'),
	path('orders/<int:pk>', views.orders, name='orders'),
	path('stripe_checkout/', views.create_checkout_session, name='create_checkout_session'),
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('core.urls')),
	path('cart/', include('cart.urls')),
	path('payment/', include('payment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/cart/models.py
from django.db import models

# Create your models here.

store/core/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create Customer Profile
class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	date_modified = models.DateTimeField(User, auto_now=True)
	phone = models.CharField(max_length=20, blank=True)
	address1 = models.CharField(max_length=200, blank=True)
	address2 = models.CharField(max_length=200, blank=True)
	city = models.CharField(max_length=200, blank=True)
	state = models.CharField(max_length=200, blank=True)
	zipcode = models.CharField(max_length=200, blank=True)
	country = models.CharField(max_length=200, blank=True)
	old_cart = models.CharField(max_length=200, blank=True, null=True)
	
	def __str__(self):
		return self.user.username

# Create a user profile by default when user sign up
def create_profile(sender, instance, created, **kwargs):
	if created:
		user_profile = Profile(user=instance)
		user_profile.save()

# Automate Profile
post_save.connect(create_profile, sender=User)

# Categories of Products
class Category(models.Model):
	name = models.CharField(max_length=50)
	image = models.ImageField(upload_to='uploads/category/')

	def __str__(self):
		return self.name
	
	class Meta:
		verbose_name_plural = 'categories'

# Customers
class Customer(models.Model):
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	phone = models.CharField(max_length=10)
	email = models.EmailField(max_length=100)
	password = models.CharField(max_length=100)

	def __str__(self):
		return f'{self.first_name} {self.last_name}'

# Our Products
class Product(models.Model):
	name = models.CharField(max_length=1000)
	price = models.DecimalField(default=0, decimal_places=2, max_digits=6)
	category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
	description = models.CharField(max_length=9000, default='', blank=True, null=True)
	specification1 = models.CharField(max_length=9000, default='', blank=True, null=True)
	specification2 = models.CharField(max_length=9000, default='', blank=True, null=True)
	specification3 = models.CharField(max_length=9000, default='', blank=True, null=True)
	specification4 = models.CharField(max_length=9000, default='', blank=True, null=True)
	specification5 = models.CharField(max_length=9000, default='', blank=True, null=True)
	warning = models.CharField(max_length=9000, default='', blank=True, null=True)
	image1 = models.ImageField(upload_to='uploads/product/')
	image2 = models.ImageField(upload_to='uploads/product/')
	image3 = models.ImageField(upload_to='uploads/product/')
	image4 = models.ImageField(upload_to='uploads/product/')

	# Sales
	is_sale = models.BooleanField(default=False)
	sale_price = models.DecimalField(default=0, decimal_places=2, max_digits=6)

	def __str__(self):
		return self.name

# Customer Order
class Order(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
	quantity = models.IntegerField(default=1)
	address = models.CharField(max_length=100, default='', blank=True)
	phone = models.CharField(max_length=20, default='', blank=True)
	date = models.DateField(default=datetime.datetime.today)
	status = models.BooleanField(default=False)

	def __str__(self):
		return self.product

store/cart/views.py
from django.shortcuts import render, get_object_or_404
from .cart import Cart
from core.models import Product
from django.http import JsonResponse
from django.contrib import messages


# Create your views here.
def cart_summary(request):
     # Get the cart
     cart = Cart(request)
     cart_products = cart.get_prods
     quantities = cart.get_quants
     totals = cart.cart_total
     return render(request, "cart_summary.html", {"cart_products": cart_products, "quantities": quantities, "totals":totals})

def cart_add(request):
    cart = Cart(request)
    
    if request.method == 'POST' and request.POST.get('action') == 'post':
        product_id = request.POST.get('product_id')
        product_qty = request.POST.get('product_qty')
        
        print("Received POST data:", request.POST)  # Debugging line

        if product_id and product_qty:
            try:
                product_id = int(product_id)
                product_qty = int(product_qty)
                product = get_object_or_404(Product, id=product_id)
                cart.add(product=product, quantity=product_qty)
                cart_quantity = cart.__len__()
                messages.success(request, ("Item added to cart successfully !"))
                return JsonResponse({'message': 'Product added to cart successfully.', 'qty': cart_quantity})
            
            except (ValueError, Product.DoesNotExist):
                return JsonResponse({'error': 'Invalid product ID or product does not exist.'}, status=400)
        else:
            return JsonResponse({'error': 'Product ID is missing.'}, status=400)
    
    return JsonResponse({'error': 'Invalid request method or action.'}, status=405)

def cart_delete(request):
    cart = Cart(request)

    if request.method == 'POST' and request.POST.get('action') == 'post':
        product_id = request.POST.get('product_id')

        if product_id:
            try:
                product_id = int(product_id)
                product = get_object_or_404(Product, id=product_id)
                cart.remove(product)
                messages.success(request, ("Item deleted !"))
                return JsonResponse({'message': 'Product removed from cart successfully.', 'product_name': product.name})

            except ValueError:
                return JsonResponse({'error': 'Invalid product ID.'}, status=400)
            except Product.DoesNotExist:
                return JsonResponse({'error': 'Product does not exist.'}, status=400)
        else:
            return JsonResponse({'error': 'Product ID is missing.'}, status=400)

    return JsonResponse({'error': 'Invalid request method or action.'}, status=405)

def cart_update(request):
    cart = Cart(request)
    
    if request.method == 'POST' and request.POST.get('action') == 'post':
        product_id = request.POST.get('product_id')
        product_qty = request.POST.get('product_qty')

        print("Received POST data:", request.POST)  # Debugging line

        if product_id and product_qty:
            try:
                product_id = int(product_id)
                product_qty = int(product_qty)
                
                product = get_object_or_404(Product, id=product_id)
                cart.update(product=product, quantity=product_qty)
                messages.success(request, ("Cart updated !"))
                return JsonResponse({'message': 'Product updated in cart successfully.', 'product_name': product.name})
            
            except ValueError:
                return JsonResponse({'error': 'Invalid product ID or quantity.'}, status=400)
            except Product.DoesNotExist:
                return JsonResponse({'error': 'Product does not exist.'}, status=400)
        else:
            return JsonResponse({'error': 'Product ID or quantity is missing.'}, status=400)
    
    return JsonResponse({'error': 'Invalid request method or action.'}, status=405)

store/core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.core.mail import send_mail
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm, UpdateUserFrom, ChangePasswordForm, UserInfoForm
from django import forms
from payment.forms import ShippingForm
from payment.models import ShippingAddress
from django.contrib import messages
from .models import Product, Category, Profile
from django.db.models import Q
import random, json
from cart.cart import Cart


def index(request):
	products = list(Product.objects.all())
	random.shuffle(products)
	return render(request, 'index.html', {'products': products})


def contact(request):
	if request.method == 'POST':
		message_name = request.POST['message-name']
		message_email = request.POST['message-email']
		message_subject = request.POST['message-subject']
		message = request.POST['message']
		send_mail( #send an email
			message_name, # subject
			message, # message
			message_email, # from email
			['yassineamrire00@gmail.com'], # To email
		)
		return render(request, 'contact.html', {'message_name': message_name})
	else:
		return render(request, 'contact.html')


def category_summary(request):
		categories = Category.objects.all()
		return render(request, 'category_summary.html', {"categories": categories})


def category(request, foo):
	foo = foo.replace('-', ' ') # Replace Hyphens with spaces
	try: # Grab category from URL
		category = Category.objects.get(name=foo) # Look Up category
		products = Product.objects.filter(category=category)
		return render(request, 'category.html', {'products': products, 'category': category})
	except:
		messages.success(request, ("Category doesn't exist !"))
		return redirect('core:index')


def product_detail(request, pk):
	products = list(Product.objects.all())
	product = Product.objects.get(id=pk)
	random.shuffle(products)
	return render(request, 'product-detail.html', {'products': products, 'product': product})


def update_user(request):
	if request.user.is_authenticated:
		current_user = User.objects.get(id=request.user.id)
		user_form = UpdateUserFrom(request.POST or None, instance=current_user)
		if user_form.is_valid():
			user_form.save()
			login(request, current_user)
			messages.success(request, "User has been updated !")
			return redirect('core:index')
		return render(request, 'my-account.html', {'user_form': user_form})
	else:
		messages.success(request, "Something went wrong !")
		return redirect('core:update_user')


def update_password(request):
	if request.user.is_authenticated:
		current_user = request.user
		if request.method == "POST":
			form = ChangePasswordForm(current_user, request.POST)
			if form.is_valid():
				form.save()
				messages.success(request, "Password has been changed !")
				return redirect('core:login')
			else:
				for error in list(form.errors.values()):
					messages.error(request, error)
					return redirect('core:update_password')
		else:
			form = ChangePasswordForm(current_user)
			return render(request, "update_password.html", {'form': form})
	else:
		messages.success(request, "Something went wrong !")
		return redirect('core:index')


def update_info(request):
    if request.user.is_authenticated:
        current_user = get_object_or_404(Profile, user__id=request.user.id) # Get Current User
        try: # Get current user shipping info
            shipping_user = ShippingAddress.objects.get(user__id=request.user.id)
        except ShippingAddress.DoesNotExist:
            shipping_user = None
        form = UserInfoForm(request.POST or None, instance=current_user) # Get Original user form
        shipping_form = ShippingForm(request.POST or None, instance=shipping_user) # Get user shipping form
        if form.is_valid() or shipping_form.is_valid():
            form.save()
            shipping_form.save()
            messages.success(request, "Info has been updated!")
            return redirect('core:index')
        return render(request, 'update_info.html', {'form': form, 'shipping_form': shipping_form})
    else:
        messages.error(request, "You need to be logged in to update your information.")
        return redirect('core:index')


def search(request):
	
	products = list(Product.objects.all()) # Determine if they filled out
	random.shuffle(products)
	if request.method == "POST":
		searched = request.POST['searched']
		searched = Product.objects.filter(Q(name__icontains=searched) | Q(description__icontains=searched)) # Query The Products DB Model
		if not searched: # Test for null
			messages.success(request, ("Product not found ... Try again !"))
			return render(request, "search.html", {'products':products})
		return render(request, "search.html", {'searched':searched, 'products':products})
	else:
		return render(request, "search.html", {'products':products})


def login_user(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			current_user = Profile.objects.get(user__id=request.user.id) # Old Cart Logic
			saved_cart = current_user.old_cart # Get their saved cart from database
			if saved_cart: # Convert database string to python dictionary
				converted_cart = json.loads(saved_cart) # Convert to dictionnary using JSON
				# Add the loaded cart dictionary to our session
				cart = Cart(request) # Get the cart
				for key, value in converted_cart.items(): # Loop through the cart and add the items from the dictionary
					cart.db_add(product=key, quantity=value)
			messages.success(request, ("You have been logged in !"))
			return redirect('core:index')
		else:
			messages.success(request, ("Incorrect username or password !"))
			return redirect('core:login')
	else:
		return render(request, 'login.html')


def logout_user(request):
	logout(request)
	messages.success(request, ("You have been logged out !"))
	return redirect('core:index')


def register_user(request):
	form = SignUpForm()
	if request.method == "POST":
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data['username']
			password = form.cleaned_data['password1']
			user = authenticate(username=username, password=password) #log in user
			login(request, user)
			messages.success(request, ("You have registered successfully ! - (Please fill out your user info)"))
			return redirect('core:update_info')
		else:
			messages.success(request, ("Your registeriation has failed !"))
			return redirect('core:register')
	else:
		return render(request, 'register.html', {'form': form})

store/core/templates/category.html
{% extends 'base.html' %}
{% load static %}      
{% block title %}{{ category }}{% endblock %}     
{% block content %}
        
        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'core:index' %}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'core:category_summary' %}">Categories</a></li>
                    <li class="breadcrumb-item active">{{ category }}</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        <!-- Product List Start -->
        <div class="product-view">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="row">
                            {% for product in products %}
                            <div class="col-md-4">
                                <div class="product-item">
                                    <div class="product-title">
                                        <a href="{% url 'core:product-detail' product.id %}">{{ product.name }}</a>
                                        <div class="ratting">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        </div>
                                    </div>
                                    <div class="product-image">
                                        <a href="{% url 'core:product-detail' product.id %}">
                                            <img src="{{ product.image1.url }}" alt="Product Image">
                                        </a>
                                        <div class="product-action">
                                            <a href="{% url 'core:product-detail' product.id %}"><i class="fa fa-search"></i></a>
                                        </div>
                                    </div>
                                    <div class="product-price">
                                        <h3><span>$</span>{{ product.price }}</h3>
                                        <a class="btn" href="{% url 'core:product-detail' product.id %}"><i class="fa fa-shopping-cart"></i>Buy Now</a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>           
                    
                    <!-- Side Bar Start -->
                    <div class="col-lg-4 sidebar">
                        <div class="sidebar-widget category">
                            <h2 class="title">Category</h2>
                            <nav class="navbar bg-light">
                                <ul class="navbar-nav">
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'core:category' 'Women-Clothes' %}"><i class="fa fa-female"></i>Women Clothes</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'core:category' 'Kids-Clothes' %}"><i class="fa fa-child"></i>Kids Clothes</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'core:category' 'Men-Clothes' %}"><i class="fa fa-tshirt"></i>Men Clothes</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'core:category' 'Cell-Phones' %}"><i class="fa fa-mobile-alt"></i>Cell Phones</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'core:category' 'Electronics-&-Accessories' %}"><i class="fa fa-microchip"></i>Electronics & Accessories</a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        
                        <div class="sidebar-widget widget-slider">
                            <div class="sidebar-slider normal-slider">
                                {% for product in products %}
                                <div class="product-item">
                                    <div class="product-title">
                                        <a href="#">{{ product.name }}</a>
                                        <div class="ratting">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        </div>
                                    </div>
                                    <div class="product-image">
                                        <a href="{% url 'core:product-detail' product.id %}">
                                            <img src="{{ product.image1.url }}" alt="Product Image">
                                        </a>
                                        <div class="product-action">
                                            <a href="{% url 'core:product-detail' product.id %}"><i class="fa fa-search"></i></a>
                                        </div>
                                    </div>
                                    <div class="product-price">
                                        <h3><span>$</span>{{ product.price }}</h3>
                                        <a class="btn" href="{% url 'core:product-detail' product.id %}"><i class="fa fa-shopping-cart"></i>Buy Now</a>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <!-- Side Bar End -->
                </div>
            </div>
        </div>
        <!-- Product List End -->  
        
        <!-- Brand Start -->
        <div class="brand">
            <div class="container-fluid">
                <div class="brand-slider">
                    <div class="brand-item"><img src="{% static 'store/img/brand-1.png' %}" alt=""></div>
                    <div class="brand-item"><img src="{% static 'store/img/brand-2.png' %}" alt=""></div>
                    <div class="brand-item"><img src="{% static 'store/img/brand-3.png' %}" alt=""></div>
                    <div class="brand-item"><img src="{% static 'store/img/brand-4.png' %}" alt=""></div>
                    <div class="brand-item"><img src="{% static 'store/img/brand-5.png' %}" alt=""></div>
                    <div class="brand-item"><img src="{% static 'store/img/brand-6.png' %}" alt=""></div>
                </div>
            </div>
        </div>
        <!-- Brand End -->
        
{% endblock %}

store/core/templates/category_summary.html
{% extends 'base.html' %}
{% load static %}      
{% block title %}Categories{% endblock %}
{% block content %}
        
        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'core:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Categories</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
		<br/><br/>
		<!-- Category Start-->
        <div class="category">
            <div class="container-fluid">
                <div class="row">
					{% for category in categories %}
                    <div class="col-md-3">
                        <div class="category-item ch-400">
                            <img src="{{ category.image.url }}" />
                            <a class="category-name" href="{% url 'core:category' category %}">
                                <p><h2><center>{{ category }}</center></h2></p>
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- Category End-->

{% endblock %}

store/core/templates/my-account.html
{% extends 'base.html' %}
{% load static %}      
{% block title %}My Account{% endblock %}
{% block content %}
        
        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'core:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Account</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->

        <!-- My Account Start -->
        <div class="my-account">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-3">
                        <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
                            <a class="nav-link active" id="account-nav" data-toggle="pill" href="#account-tab" role="tab"><i class="fa fa-user"></i>Account Details</a>
                            <a class="nav-link" href="{% url 'core:update_password' %}"><i class="fa fa-lock"></i>Update Password</a>
                            {% if user.is_superuser %}
                            <a class="nav-link" href="{% url 'payment:shipped_dash' %}"><i class="fa fa fa-truck"></i>Shipped Orders</a>
                            <a class="nav-link" href="{% url 'payment:not_shipped_dash' %}"><i class="fa fa-archive"></i>Unshipped Orders</a>
                            {% endif %}
                            <a class="nav-link" href="{% url 'core:logout' %}"><i class="fa fa-sign-out-alt"></i>Logout</a>
                        </div>
                    </div>
                    <div class="col-md-9">
                        <div class="tab-content">
                            <div class="tab-pane fade show active" id="account-tab" role="tabpanel" aria-labelledby="account-nav">
                                <form method="POST" action="{% url 'core:update_user' %}">
                                    {% csrf_token %}
                                    {{ user_form.as_p }}
                                    <div class="row">
                                        <div class="col-md-12">
                                            <button class="btn">Update Profile</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- My Account End -->
        <br/><br/>
        <br/><br/>
        <br/><br/>
        
{% endblock %}

store/core/templates/navbar.html
<!-- Nav Bar Start -->
<div class="nav">
	<div class="container-fluid">
		<nav class="navbar navbar-expand-md bg-dark navbar-dark">
			<a href="#" class="navbar-brand">MENU</a>
			<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
				<span class="navbar-toggler-icon"></span>
			</button>
		
			<div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
				<div class="navbar-nav mr-auto">
					<a href="{% url 'core:index' %}" class="nav-item nav-link">Home</a>
					<a href="{% url 'cart:cart_summary' %}" class="nav-item nav-link">Cart</a>
					<div class="nav-item dropdown">
						<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Categories</a>
						<div class="dropdown-menu">
							<a href="{% url 'core:category_summary' %}" class="dropdown-item">All Categories</a>
							<a href="{% url 'core:category' 'Kids-Clothes' %}" class="dropdown-item">Kids Clothes</a>
							<a href="{% url 'core:category' 'Men-Clothes' %}" class="dropdown-item">Men Clothes</a>
							<a href="{% url 'core:category' 'Women-Clothes' %}" class="dropdown-item">Women Clothes</a>
							<a href="{% url 'core:category' 'Cell-Phones' %}" class="dropdown-item">Cell Phones</a>
							<a href="{% url 'core:category' 'Electronics-&-Accessories' %}" class="dropdown-item">Electronics & Accessories</a>
						</div>
					</div>
					<a href="{% url 'core:contact' %}" class="nav-item nav-link">Contact Us</a>
				</div>
				<div class="navbar-nav ml-auto">
					<div class="nav-item dropdown">
						<a href="{% url 'core:update_user' %}" class="nav-link dropdown-toggle" data-toggle="dropdown">User Account</a>
						<div class="dropdown-menu">
							{% if user.is_authenticated %}
							<a href="{% url 'core:update_info' %}" class="dropdown-item">Profile</a>
							<a href="{% url 'core:update_user' %}" class="dropdown-item">Account</a>
							<a href="{% url 'core:logout' %}" class="dropdown-item">Logout</a>
							{% else %}
							<a href="{% url 'core:login' %}" class="dropdown-item">Login</a>
							<a href="{% url 'core:register' %}" class="dropdown-item">Register</a>
							{% endif %}
						</div>
					</div>
				</div>
			</div>
		</nav>
	</div>
</div>
<!-- Nav Bar End -->