store/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart_summary, name="cart_summary"),
	path('add/', views.cart_add, name="cart_add"),
	path('delete/', views.cart_delete, name="cart_delete"),
	path('update/', views.cart_update, name="cart_update"),
]

store/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
	path('', views.index, name='index'),
	path('index/', views.index, name='index'),
	path('contact/', views.contact, name='contact'),
	path('category/<str:foo>', views.category, name='category'),
	path('product-detail/<int:pk>', views.product_detail, name='product-detail'),
	path('update_user/', views.update_user, name='update_user'),
	path('update_password/', views.update_password, name='update_password'),
	path('update_info/', views.update_info, name='update_info'),
	path('login/', views.login_user, name='login'),
	path('logout/', views.logout_user, name='logout'),
	path('register/', views.register_user, name='register'),
	path('category_summary/', views.category_summary, name='category_summary'),
	path('search/', views.search, name='search'),
]

store/payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
	path('payment_success', views.payment_success, name='payment_success'),
	path('payment_failed', views.payment_failed, name='payment_failed'),
	path('checkout', views.checkout, name='checkout'),
	path('billing_info', views.billing_info, name='billing_info'),
	path('process_order', views.process_order, name='process_order'),
	path('shipped_dash', views.shipped_dash, name='shipped_dash'),
	path('not_shipped_dash', views.not_shipped_dash, name='not_shipped_dash'),
	path('orders/<int:pk>', views.orders, name='orders'),
	path('stripe_checkout/', views.create_checkout_session, name='create_checkout_session'),
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('core.urls')),
	path('cart/', include('cart.urls')),
	path('payment/', include('payment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/payment/models.py
from django.db import models
from django.contrib.auth.models import User
from core.models import Product
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
import datetime

# Create your models here.
class ShippingAddress(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
	shipping_full_name = models.CharField(max_length=255)
	shipping_email = models.CharField(max_length=255)
	shipping_address1 = models.CharField(max_length=255)
	shipping_address2 = models.CharField(max_length=255, null=True, blank=True)
	shipping_city = models.CharField(max_length=255)
	shipping_state = models.CharField(max_length=255, null=True, blank=True)
	shipping_zipcode = models.CharField(max_length=255, null=True, blank=True)
	shipping_country = models.CharField(max_length=255)

	# Don't pluralize address
	class Meta:
		verbose_name_plural = "Shipping Address"

	def __str__(self):
		return f'Shipping Address - {str(self.id)}'

# Create a user Shipping Address by default when user signs up
def create_shipping(sender, instance, created, **kwargs):
	if created:
		user_shipping = ShippingAddress(user=instance)
		user_shipping.save()

# Automate the profile thing
post_save.connect(create_shipping, sender=User)


class Order(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
	full_name = models.CharField(max_length=250)
	email = models.EmailField(max_length=250)
	shipping_address = models.TextField(max_length=15000)
	amount_paid = models.DecimalField(max_digits=7, decimal_places=2)
	date_ordered = models.DateTimeField(auto_now_add=True)	
	shipped = models.BooleanField(default=False)
	date_shipped = models.DateTimeField(blank=True, null=True)
	
	def __str__(self):
		return f'Order - {str(self.id)}'
	
# Auto Add shipping Date
@receiver(pre_save, sender=Order)
def set_shipped_date_on_update(sender, instance, **kwargs):
	if instance.pk:
		now = datetime.datetime.now()
		obj = sender._default_manager.get(pk=instance.pk)
		if instance.shipped and not obj.shipped:
			instance.date_shipped = now
	

class OrderItem(models.Model):
	order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
	product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
	quantity = models.PositiveBigIntegerField(default=1)
	price = models.DecimalField(max_digits=7, decimal_places=2)

	def __str__(self):
		return f'Order Item - {str(self.id)}'

store/payment/forms.py
from django import forms
from .models import ShippingAddress

class ShippingForm(forms.ModelForm):
	shipping_full_name = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Full Name'}), required=True)
	shipping_email = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}), required=True)
	shipping_address1 = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Address1'}), required=True)
	shipping_address2 = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Address2'}), required=False)
	shipping_city = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'City'}), required=True)
	shipping_state = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'State'}), required=False)
	shipping_zipcode = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Zipcode'}), required=False)
	shipping_country = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Country'}), required=True)

	class Meta:
		model = ShippingAddress
		fields = ['shipping_full_name', 'shipping_email', 'shipping_address1', 'shipping_address2', 'shipping_city', 'shipping_state', 'shipping_zipcode', 'shipping_country']
		exclude = ['user',]

class PaymentForm(forms.Form):
	card_name =  forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Name On Card'}), required=True)
	card_number =  forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Card Number'}), required=True)
	card_exp_date =  forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Expiration Date'}), required=True)
	card_cvv_number =  forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'CVV Code'}), required=True)
	card_address1 =  forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Billing Address 1'}), required=True)
	card_address2 =  forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Billing Address 2'}), required=False)
	card_city =  forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Billing City'}), required=True)
	card_state = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Billing State'}), required=True)
	card_zipcode =  forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Billing Zipcode'}), required=True)
	card_country =  forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Billing Country'}), required=True)

store/payment/views.py
from django.shortcuts import render, redirect
from payment.forms import ShippingForm, PaymentForm
from payment.models import ShippingAddress, Order, OrderItem
from django.contrib.auth.models import User
from cart.cart import Cart
from django.contrib import messages
from core.models import Product, Profile
import datetime
# Stripe
import stripe
from django.conf import settings
from django.shortcuts import render, redirect
from django.urls import reverse


stripe.api_key = settings.STRIPE_SECRET_KEY


def payment_success(request):
	return render(request, "payment/payment_success.html", {})


def payment_failed(request):
	return render(request, "payment/payment_failed.html", {})


def checkout(request):
	cart = Cart(request) # Get the cart
	cart_products = cart.get_prods
	quantities = cart.get_quants
	totals = cart.cart_total()
	if request.user.is_authenticated:
		# Checkout as logged in user
		shipping_user = ShippingAddress.objects.get(user__id=request.user.id) # Shipping User
		shipping_form = ShippingForm(request.POST or None, instance=shipping_user) # Shipping Form
		return render(request, "payment/checkout.html", {"cart_products":cart_products, "quantities":quantities, "totals":totals, "shipping_form":shipping_form })
	else:
		shipping_form = ShippingForm(request.POST or None) # Checkout as guest
		return render(request, "payment/checkout.html", {"cart_products":cart_products, "quantities":quantities, "totals":totals, "shipping_form":shipping_form})


def billing_info(request):
	if request.POST:
		cart = Cart(request) # Get the cart
		cart_products = cart.get_prods
		quantities = cart.get_quants
		totals = cart.cart_total()
		my_shipping = request.POST # Create a session with Shipping Info
		request.session['my_shipping'] = my_shipping
		if request.user.is_authenticated: # Check to see if user is logged in
			billing_form = PaymentForm() # Get The Billing Form
			return render(request, "payment/billing_info.html", {"cart_products":cart_products, "quantities":quantities, "totals":totals, "shipping_info":request.POST, "billing_form":billing_form})
		else: # Not logged in
			billing_form = PaymentForm() # Get The Billing Form
			return render(request, "payment/billing_info.html", {"cart_products":cart_products, "quantities":quantities, "totals":totals, "shipping_info":request.POST, "billing_form":billing_form})
	else:
		messages.success(request, "Access Denied")
		return redirect('core:index')


def process_order(request):
	if request.POST:
		cart = Cart(request) # Get the cart
		cart_products = cart.get_prods
		quantities = cart.get_quants
		totals = cart.cart_total()
		payment_form = PaymentForm(request.POST or None) # Get Billing Info from the last page
		my_shipping = request.session.get('my_shipping') # Get Shipping Session Data
		full_name = my_shipping['shipping_full_name'] # Gather Order Info
		email = my_shipping['shipping_email']
		# Create Shipping Address from session info
		shipping_address = f"{my_shipping['shipping_address1']}\n{my_shipping['shipping_address2']}\n{my_shipping['shipping_city']}\n{my_shipping['shipping_state']}\n{my_shipping['shipping_zipcode']}\n{my_shipping['shipping_country']}"
		amount_paid = totals
		if request.user.is_authenticated: # Create an Order
			user = request.user # logged in
			create_order = Order(user=user, full_name=full_name, email=email, shipping_address=shipping_address, amount_paid=amount_paid) # Create Order
			create_order.save()
			# Add order items
			order_id = create_order.pk # Get the order ID
			for product in cart_products(): # Get product Info
				product_id = product.id # Get product ID
				price = product.price # Get product price
				for key,value in quantities().items(): # Get quantity
					if int(key) == product.id:
						create_order_item = OrderItem(order_id=order_id, product_id=product_id, user=user, quantity=value, price=price) # Create order item
						create_order_item.save()
			# Delete our cart
			for key in list(request.session.keys()):
				if key == "session_key":
					del request.session[key] # Delete the key
			current_user = Profile.objects.filter(user__id=request.user.id) # Delete Cart from Database (old_cart field)
			current_user.update(old_cart="") # Delete shopping cart in database (old_cart field)
			messages.success(request, "Order Placed !")
			return redirect('core:index')
		else: # not logged in
			create_order = Order(full_name=full_name, email=email, shipping_address=shipping_address, amount_paid=amount_paid) # Create Order
			create_order.save()
			# Add order items
			order_id = create_order.pk # Get the order ID
			for product in cart_products(): # Get product Info
				product_id = product.id # Get product ID
				if product.is_sale: # Get product price
					price = product.sale_price
				else:
					price = product.price
				for key,value in quantities().items(): # Get quantity
					if int(key) == product.id:
						create_order_item = OrderItem(order_id=order_id, product_id=product_id, quantity=value, price=price) # Create order item
						create_order_item.save()
			# Delete our cart
			for key in list(request.session.keys()):
				if key == "session_key":
					del request.session[key] # Delete the key
			current_user = Profile.objects.filter(user__id=request.user.id) # Delete Cart from Database (old_cart field)
			current_user.update(old_cart="") # Delete shopping cart in database (old_cart field)
			messages.success(request, "Order Placed !")
			return redirect('core:index')
	else:
		messages.success(request, "Access Denied !")
		return redirect('core:index')


def not_shipped_dash(request):
	if request.user.is_authenticated and request.user.is_superuser:
		orders = Order.objects.filter(shipped=False)
		if request.POST:
			status = request.POST['shipping_status']
			num = request.POST['num']
			order = Order.objects.filter(id=num) # Grab the order
			now = datetime.datetime.now() # Grab date and time
			order.update(shipped=True, date_shipped=now) # Update order
			messages.success(request, "Shipping Status Updated")
			return redirect('core:index')
		return render(request, "payment/not_shipped_dash.html", {"orders":orders})
	else:
		messages.success(request, "Access Denied")
		return redirect('core:index')


def shipped_dash(request):
	if request.user.is_authenticated and request.user.is_superuser:
		orders = Order.objects.filter(shipped=True)
		if request.POST:
			status = request.POST['shipping_status']
			num = request.POST['num']
			order = Order.objects.filter(id=num) # Grab the order
			now = datetime.datetime.now() # Grab date and time
			order.update(shipped=False, date_shipped=now) # Update order
			messages.success(request, "Shipping Status Updated")
			return redirect('core:index')
		return render(request, "payment/shipped_dash.html", {"orders":orders})
	else:
		messages.success(request, "Access Denied")
		return redirect('core:index')
	

def orders(request, pk):
	if request.user.is_authenticated and request.user.is_superuser:
		order = Order.objects.get(id=pk) # Get the order
		items = OrderItem.objects.filter(order=pk) # Get the order items
		if request.POST:
			status = request.POST['shipping_status']
			if status == "true":
				order = Order.objects.filter(id=pk) # Get the order
				now = datetime.datetime.now() # Update shipping date
				order.update(shipped=True, date_shipped=now) # Update the status
			else:
				order = Order.objects.filter(id=pk) # Get the order
				order.update(shipped=False) # Update the status
			messages.success(request, "Shipping Status Updated")
			return redirect('core:index')
		return render(request, 'payment/orders.html', {"order":order, "items":items})
	else:
		messages.success(request, "Access Denied")
		return redirect('core:index')
	

# Stripe
def create_checkout_session(request):
	cart = Cart(request) # Initialize the cart
	products = cart.get_prods() # Get ids from cart
	quantities = cart.get_quants()
	line_items = [] # Create line items for each product in the cart
	for product in products:
		product_id_str = str(product.id)
		quantity = quantities.get(product_id_str, 0)
		line_item = {
            'price_data': {
                'currency': 'usd',
                'product_data': {
                    'name': product.name,  # Assuming product has a name attribute
                },
                'unit_amount': int(product.price * 100),  # Amount in cents
            },
            'quantity': quantity,
        }
		line_items.append(line_item)
	session = stripe.checkout.Session.create( # Create a new Checkout Session
        payment_method_types=['card'],
        line_items=line_items,
        mode='payment',
        success_url=request.build_absolute_uri(reverse('payment:payment_success')),
        cancel_url=request.build_absolute_uri(reverse('payment:payment_failed')),
    )
	return redirect(session.url, code=303) # Redirect to the Stripe Checkout page

def stripe_checkout(request):
	return render(request, "payment/stripe_checkout.html", {})

store/payment/templates/payment/billing_info.html
{% extends 'base.html' %}
{% load static %}      
{% block title %}Billing Info{% endblock %}
{% block content %}

        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'core:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Billing Info</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
       <!-- Checkout Start -->
       <div class="checkout">
        <div class="container-fluid"> 
            <div class="row">
                <div class="col-lg-8">
                    <div class="checkout-payment">
                        
                        <h1>Cart Items</h1>
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>Product</th>
                                        <th>Price</th>
                                        <th>Quantity</th>
                                    </tr>
                                </thead>
                                <tbody class="align-middle">
                                    {% if cart_products %}
                                    {% for product in cart_products %}
                                    <tr>
                                        <td>
                                            <div class="img">
                                                <a href="{% url 'core:product-detail' product.id %}"><img src="{{ product.image1.url }}" alt="Image" style="width: 150px; height: 150px;"></a>
                                                <p><strong>{{ product.name }}</strong></p>
                                            </div>
                                        </td>
                                        <td>${{ product.price }}</td>
                                        <td>
                                            <div class="qty">
                                                <input id="select{{ product.id }}"
                                                {% if quantities %}
                                                {% for key, value in quantities.items %}
                                                    {% if key == product.id|slugify %}
                                                        value="{{ value }}"
                                                    {% endif %}
                                                {% endfor %}
                                                {% else %}
                                                value="1"
                                                {% endif %}
                                                >
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    {% endif %}
                                </tbody>
                            </table>
                        </div>
                        <div class="checkout-btn">
                            <a href="{% url 'payment:create_checkout_session' %}"><button>Place Order</button></a>
                        </div><br/>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="checkout-inner">
                        <div class="checkout-payment">
                            <div class="payment-methods">
                                <h1>Cart Total</h1>
                                <p class="sub-total">Number of Items<span>&nbsp;{{ cart|length }}</span></p>
                            <p class="ship-cost">Shipping Cost<span>&nbsp;$1</span></p>
                            <h2>Grand Total<span>&nbsp;${{ totals }}</span></h2>
                            </div>
                            <div class="checkout-btn">
                                <a href="{% url 'cart:cart_summary' %}"><button>Update Cart</button></a>
                            </div>
                        </div>
                        <br/><br/><br/>
                        <div class="checkout-payment">
                            <div class="payment-methods">
                                <h1>Shipping Info</h1>
                                <b>Name: </b><br/><mark>{{ shipping_info.shipping_full_name }}</mark><br/><br/>
                                <b>Email: </b><br/><mark>{{ shipping_info.shipping_email }}</mark><br/><br/>
                                <b>Address 1: </b><br/><mark>{{ shipping_info.shipping_address1 }}</mark><br/><br/>
                                <b>Address 2: </b><br/><mark>{{ shipping_info.shipping_address2 }}</mark><br/><br/>
                                <b>City: </b><br/><mark>{{ shipping_info.shipping_city }}</mark><br/><br/>
                                <b>State: </b><br/><mark>{{ shipping_info.shipping_state }}</mark><br/><br/>
                                <b>ZipCode: </b><br/><mark>{{ shipping_info.shipping_zipcode }}</mark><br/><br/>
                                <b>Country: </b><br/><mark>{{ shipping_info.shipping_country }}</mark><br/><br/>
                            </div>
                            <div class="checkout-btn">
                                <a href="{% url 'payment:checkout' %}"><button>Update Info</button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Checkout End -->
       
        
{% endblock %}

store/payment/templates/payment/payment_success.html
{% extends 'base.html' %}
{% load static %}      
{% block title %}Payment Success{% endblock %}
{% block content %}

        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'core:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Payment Success</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        <h1>Payment Successful</h1>
        <p>Thank you for your purchase!</p>
        
{% endblock %}

store/payment/templates/payment/process_failed.html
{% extends 'base.html' %}
{% load static %}      
{% block title %}Payment Failed{% endblock %}
{% block content %}

        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'core:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Payment Failed</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        <h1>Payment Failed</h1>
        <p>Your payment was not completed. Please try again.</p>
        
{% endblock %}

store/payment/templates/payment/process_order.html
{% extends 'base.html' %}
{% load static %}      
{% block title %}Process Order{% endblock %}
{% block content %}

        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'core:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Process Order</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        <!-- Checkout Start -->
        <div class="checkout">
            <div class="container-fluid"> 
                <div class="row">
                    {% if cart_products %}
                    <div class="col-lg-8">
                        <div class="cart-page-inner">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th>Product</th>
                                            <th>Price</th>
                                            <th>Quantity</th>
                                        </tr>
                                    </thead>
                                    <tbody class="align-middle">
                                        {% for product in cart_products %}
                                        <tr>
                                            <td>
                                                <div class="img">
                                                    <a href="{% url 'core:product-detail' product.id %}"><img src="{{ product.image1.url }}" alt="Image" style="width: 150px; height: 150px;"></a>
                                                    <p><strong>{{ product.name }}</strong></p>
                                                </div>
                                            </td>
                                            <td>${{ product.price }}</td>
                                            <td>
                                                <div class="qty">
                                                    <button class="btn-minus"><i class="fa fa-minus"></i></button>
                                                    <input id="select{{ product.id }}" type="number" min="1"
                                                    {% if quantities %}
                                                    {% for key, value in quantities.items %}
                                                        {% if key == product.id|slugify %}
                                                            value="{{ value }}"
                                                        {% endif %}
                                                    {% endfor %}
                                                    {% else %}
                                                    value="1"
                                                    {% endif %}
                                                    >
                                                    <button class="btn-plus"><i class="fa fa-plus"></i></button>
                                                </div>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
						<div class="checkout-payment">
							<div class="checkout-btn">
								<a href="{% url 'cart:cart_summary' %}" class="btn"><i class="fa fa-shopping-cart"></i>&nbsp;Update Cart</a>
							</div>
						</div>
                        <div class="register-form">
                            <form method="POST" action="{% url 'payment:billing_info' %}">
                                <br/><h4><strong>Shipping Information</strong></h4><br/>
                                {% csrf_token %}
                                <strong>Name: </strong>{{ shipping_info.shipping_full_name }}<br/>
                                <strong>Email: </strong>{{ shipping_info.shipping_email }}<br/>
                                <strong>Address 1: </strong>{{ shipping_info.shipping_address1 }}<br/>
                                <strong>Address 2: </strong>{{ shipping_info.shipping_address2 }}<br/>
                                <strong>City: </strong>{{ shipping_info.shipping_city }}<br/>
                                <strong>State: </strong>{{ shipping_info.shipping_state }}<br/>
								<strong>ZipCode: </strong>{{ shipping_info.shipping_zipcode }}<br/>
                                <strong>Country: </strong>{{ shipping_info.shipping_country }}<br/><br/>
                                <div class="checkout-payment">
                                    <div class="checkout-btn">
                                        <a href="{% url 'payment:checkout' %}" type="submit" class="btn">Update Shipping</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <br/>
						<div class="register-form">
                            <form method="POST" action="{% url 'payment:process_order' %}">
                                <br/><h4><strong>Billing Information</strong></h4><br/>
                                {% csrf_token %}
                                {{ billing_form.as_p }}
                                <div class="checkout-payment">
                                    <div class="checkout-btn">
                                        <button type="submit" class="btn">Place Order</button>
                                    </div>
                                </div>
								<br/>
                            </form>
                        </div>
                    </div>
                    {% endif %}
                    <div class="col-lg-4">
                        <div class="checkout-inner">
                            <div class="checkout-summary">
                                <h1>Cart Total</h1>
                                <p class="sub-total">Number of Items<span>{{ cart|length }}</span></p>
                                <p class="ship-cost">Shipping Cost<span>$1</span></p>
                                <h2>Grand Total<span>${{ totals }}</span></h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Checkout End -->
        
{% endblock %}

store/payment/templates/payment/stripe_checkout.html
{% extends 'base.html' %}
{% load static %}      
{% block title %}Stripe Checkout{% endblock %}
{% block content %}

        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'core:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Stripe Checkout</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        <h1>Stripe Checkout</h1>
        <p>
            <form action="{% url 'payment:create_checkout_session' %}" method="POST">
                {% csrf_token %}
                <button type="submit">Pay Now</button>
            </form>
        </p>
        
{% endblock %}